server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: true
  application:
    name: RATING-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    service-url:
      deafultZone: http://localhost:8761/eureka